-- STAGING ONLY. DESIGN ONLY. NOT AUTHORIZED. NOT EXECUTED.
-- MUST NEVER RUN ON PRODUCTION.
-- NOT APPLICABLE: authoritative production metadata reports zero public sequences.
-- Generate no CREATE SEQUENCE or OWNED BY statements.
