-- STAGING ONLY. DESIGN ONLY. NOT AUTHORIZED. NOT EXECUTED.
-- MUST NEVER RUN ON PRODUCTION.
-- Generated only from safety-reviewed catalog metadata and repository-confirmed later alterations.

CREATE TABLE "public"."programs" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  CONSTRAINT "programs_code_key" UNIQUE (code),
  CONSTRAINT "programs_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."seasons" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "program_id" uuid,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "status" "public"."season_status" DEFAULT 'draft'::season_status,
  "starts_on" date,
  "ends_on" date,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "seasons_code_key" UNIQUE (code),
  CONSTRAINT "seasons_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."intake_batches" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "season_id" uuid NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "intake_batches_code_not_blank" CHECK (length(TRIM(BOTH FROM code)) > 0),
  CONSTRAINT "intake_batches_name_not_blank" CHECK (length(TRIM(BOTH FROM name)) > 0),
  CONSTRAINT "intake_batches_pkey" PRIMARY KEY (id),
  CONSTRAINT "intake_batches_season_code_unique" UNIQUE (season_id, code)
);

CREATE TABLE "public"."people" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_person_temp_id" text,
  "full_name" text NOT NULL,
  "full_name_normalized" text,
  "email_primary" "public"."citext" NOT NULL,
  "phone_primary" text,
  "phone_raw" text,
  "gender" "public"."gender_type",
  "date_of_birth" date,
  "facebook_url" text,
  "preferred_language" text,
  "consent_pdpa" boolean,
  "consent_pdpa_at" timestamp with time zone,
  "consent_marketing_email" boolean,
  "source_sheets" text,
  "source_sheet" text,
  "source_row_id" integer,
  "data_quality_flags" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "people_email_primary_key" UNIQUE (email_primary),
  CONSTRAINT "people_legacy_person_temp_id_key" UNIQUE (legacy_person_temp_id),
  CONSTRAINT "people_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."person_roles" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "person_id" uuid NOT NULL,
  "role" "public"."role_type" NOT NULL,
  "season_id" uuid,
  "status" "public"."role_status",
  "source_sheet" text,
  "source_row_id" integer,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "person_roles_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."mentor_profiles" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "person_id" uuid,
  "mentor_code" text,
  "bio_url" text,
  "company_current" text,
  "title_current" text,
  "alma_mater" text,
  "first_joined_year" integer,
  "years_experience_min" integer,
  "years_experience_text" text,
  "interests_text" text,
  "support_team_lead" boolean,
  "admin_notes" text,
  "source_sheet" text,
  "source_row_id" integer,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "current_company" text,
  "current_title" text,
  "industry" text,
  "function_area" text,
  "years_of_experience" integer,
  "years_in_vam" integer,
  "capacity_target" integer,
  "seniority_level" text,
  "first_vam_season" text,
  "source_application_id" uuid,
  "intake_batch_id" uuid,
  CONSTRAINT "mentor_profiles_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."mentee_profiles" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "person_id" uuid,
  "mentee_code" text,
  "school_code" text,
  "school_raw" text,
  "mssv" text,
  "mssv_raw" text,
  "major" text,
  "class_cohort" text,
  "gpa_4" text,
  "has_prior_season" boolean,
  "source_sheet" text,
  "source_row_id" integer,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "university" text,
  "career_interest" text,
  "target_industry" text,
  "year_of_study" text,
  "support_team" text,
  "source_application_id" uuid,
  "intake_batch_id" uuid,
  CONSTRAINT "mentee_profiles_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."applications" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_application_temp_id" text,
  "person_id" uuid,
  "season_id" uuid,
  "role_applied" "public"."role_type",
  "submitted_at" date,
  "sbd" text,
  "consent_pdpa" boolean,
  "consent_pdpa_at" timestamp with time zone,
  "acquisition_channel" text,
  "final_status" "public"."application_status",
  "profile_url" text,
  "source_sheet" text,
  "source_row_id" integer,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "full_name" text,
  "email_primary" text,
  "phone_primary" text,
  "gender" text,
  "intake_batch_id" uuid,
  "status" text DEFAULT 'submitted'::text,
  "raw_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "consent_data_storage" boolean DEFAULT false NOT NULL,
  "source" text DEFAULT 'manual'::text,
  "score_total" integer,
  "score_breakdown" jsonb DEFAULT '{}'::jsonb,
  "internal_notes" jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT "applications_legacy_application_temp_id_key" UNIQUE (legacy_application_temp_id),
  CONSTRAINT "applications_pkey" PRIMARY KEY (id),
  CONSTRAINT "applications_status_check" CHECK (status IS NULL OR (status = ANY (ARRAY['submitted'::text, 'under_data_check'::text, 'ready_for_screening'::text, 'screening_assigned'::text, 'screening_in_progress'::text, 'screening_completed'::text, 'screening_passed'::text, 'invited_to_meeting'::text, 'invited_to_orientation'::text, 'invited_to_interview'::text, 'interview_scheduled'::text, 'interview_completed'::text, 'interview_passed'::text, 'approved_as_mentor'::text, 'approved_as_mentee'::text, 'waitlisted'::text, 'rejected_or_not_fit'::text, 'needs_more_review'::text, 'withdrawn'::text])))
);

CREATE TABLE "public"."application_answers" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "application_id" uuid,
  "question_key" text,
  "question_label" text,
  "value_text" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "application_answers_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_event_temp_id" text,
  "season_id" uuid,
  "event_name" text,
  "event_type" "public"."event_type",
  "starts_at" timestamp with time zone,
  "source_notes" text,
  "source_sheet" text,
  "source_row_id" integer,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "intake_batch_id" uuid,
  "status" text DEFAULT 'active'::text NOT NULL,
  "registration_required" boolean DEFAULT false NOT NULL,
  "approval_required" boolean DEFAULT false NOT NULL,
  "allow_walk_in" boolean DEFAULT true NOT NULL,
  "checkin_mode" text DEFAULT 'open'::text NOT NULL,
  "capacity_limit_enabled" boolean DEFAULT false NOT NULL,
  "capacity_limit" integer,
  "checkin_window_enabled" boolean DEFAULT false NOT NULL,
  "checkin_opens_at" timestamp with time zone,
  "checkin_closes_at" timestamp with time zone,
  "proof_required_for_registration" boolean DEFAULT false NOT NULL,
  "proof_instruction" text,
  "fee_required" boolean DEFAULT false NOT NULL,
  "fee_amount" numeric(10,2),
  "fee_currency" text DEFAULT 'VND'::text NOT NULL,
  "fee_description" text,
  "payment_instruction" text,
  "payment_proof_required" boolean DEFAULT false NOT NULL,
  "collect_speaker_questions" boolean DEFAULT false NOT NULL,
  "speaker_question_prompt" text,
  "show_no_show_policy" boolean DEFAULT false NOT NULL,
  "no_show_policy_text" text,
  "show_student_id_field" boolean DEFAULT true NOT NULL,
  "student_id_required" boolean DEFAULT false NOT NULL,
  "show_mentee_code_field" boolean DEFAULT false NOT NULL,
  "show_school_field" boolean DEFAULT true NOT NULL,
  "show_program_field" boolean DEFAULT true NOT NULL,
  "show_role_field" boolean DEFAULT false NOT NULL,
  "show_notes_field" boolean DEFAULT true NOT NULL,
  "public_description" text,
  "event_description" text,
  "waitlist_enabled" boolean DEFAULT false NOT NULL,
  "proof_required" boolean DEFAULT false NOT NULL,
  "proof_label" text,
  "proof_description" text,
  "proof_required_for_checkin" boolean DEFAULT false NOT NULL,
  "question_collection_enabled" boolean DEFAULT false NOT NULL,
  "speaker_question_label" text,
  "no_show_policy_enabled" boolean DEFAULT false NOT NULL,
  "mentee_code_required" boolean DEFAULT false NOT NULL,
  "show_role_text_field" boolean DEFAULT false NOT NULL,
  "meal_option_enabled" boolean DEFAULT false NOT NULL,
  "meal_label" text,
  "meal_fee_amount" numeric(10,2),
  "meal_fee_currency" text DEFAULT 'VND'::text NOT NULL,
  "meal_payment_instruction" text,
  "meal_payment_proof_required" boolean DEFAULT true NOT NULL,
  CONSTRAINT "events_legacy_event_temp_id_key" UNIQUE (legacy_event_temp_id),
  CONSTRAINT "events_pkey" PRIMARY KEY (id),
  CONSTRAINT "events_status_check" CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text]))
);

CREATE TABLE "public"."event_links" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "event_id" uuid NOT NULL,
  "link_type" text NOT NULL,
  "token" uuid DEFAULT gen_random_uuid() NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "opens_at" timestamp with time zone,
  "closes_at" timestamp with time zone,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "event_links_event_id_link_type_key" UNIQUE (event_id, link_type),
  CONSTRAINT "event_links_link_type_check" CHECK (link_type = ANY (ARRAY['registration'::text, 'checkin'::text])),
  CONSTRAINT "event_links_pkey" PRIMARY KEY (id),
  CONSTRAINT "event_links_token_key" UNIQUE (token)
);

CREATE TABLE "public"."event_registrations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_event_registration_temp_id" text,
  "event_id" uuid,
  "person_id" uuid,
  "registration_status" text,
  "source_notes" text,
  "source_sheet" text,
  "source_row_id" integer,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "event_link_id" uuid,
  "linked_person_id" uuid,
  "email" text,
  "full_name" text,
  "phone" text,
  "student_id" text,
  "school" text,
  "program_of_study" text,
  "role_text" text,
  "notes" text,
  "consent_given" boolean DEFAULT false NOT NULL,
  "registration_source" text DEFAULT 'public_form'::text NOT NULL,
  "attendance_status" text DEFAULT 'pending'::text NOT NULL,
  "is_walk_in" boolean DEFAULT false NOT NULL,
  "registered_at" timestamp with time zone DEFAULT now() NOT NULL,
  "checked_in_at" timestamp with time zone,
  "checkin_source" text,
  "match_method" text DEFAULT 'unlinked'::text NOT NULL,
  "match_review_status" text DEFAULT 'pending_review'::text NOT NULL,
  "matched_at" timestamp with time zone,
  "mentee_code" text,
  "proof_url" text,
  "proof_note" text,
  "proof_status" text DEFAULT 'not_required'::text NOT NULL,
  "review_status" text DEFAULT 'pending'::text NOT NULL,
  "review_note" text,
  "reviewed_at" timestamp with time zone,
  "reviewed_by" uuid,
  "payment_status" text DEFAULT 'not_required'::text NOT NULL,
  "payment_proof_url" text,
  "no_show_flagged" boolean DEFAULT false NOT NULL,
  "blacklist_flag" boolean DEFAULT false NOT NULL,
  "confirmed_at" timestamp with time zone,
  "confirmed_by" uuid,
  "cancelled_at" timestamp with time zone,
  "cancelled_by" uuid,
  "cancel_reason" text,
  "waitlist_position" integer,
  "waitlisted_at" timestamp with time zone,
  "waitlisted_by" uuid,
  "rejected_at" timestamp with time zone,
  "rejected_by" uuid,
  "reject_reason" text,
  "speaker_question" text,
  "proof_reviewed_at" timestamp with time zone,
  "proof_reviewed_by" uuid,
  "proof_review_note" text,
  "payment_proof_note" text,
  "payment_confirmed_at" timestamp with time zone,
  "payment_confirmed_by" uuid,
  "payment_rejected_at" timestamp with time zone,
  "payment_rejected_by" uuid,
  "payment_rejection_note" text,
  "no_show_flagged_at" timestamp with time zone,
  "no_show_flagged_by" uuid,
  "blacklist_note" text,
  "meal_selected" boolean DEFAULT false NOT NULL,
  "meal_label" text,
  "meal_fee_amount" numeric(10,2),
  "meal_fee_currency" text,
  CONSTRAINT "event_registrations_legacy_event_registration_temp_id_key" UNIQUE (legacy_event_registration_temp_id),
  CONSTRAINT "event_registrations_pkey" PRIMARY KEY (id),
  CONSTRAINT "event_registrations_registration_status_check" CHECK (registration_status = ANY (ARRAY['registered'::text, 'cancelled'::text, 'pending_review'::text, 'confirmed'::text, 'waitlisted'::text, 'rejected'::text]))
);

CREATE TABLE "public"."event_participations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "event_id" uuid,
  "season_id" uuid,
  "person_id" uuid,
  "role_at_event" text,
  "registration_status" text DEFAULT 'registered'::text NOT NULL,
  "attendance_status" text DEFAULT 'registered_absent'::text NOT NULL,
  "attendance_date" date,
  "recap_url" text,
  "excuse_reason" text,
  "admin_notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "captured_by" text,
  "walk_in" boolean DEFAULT false NOT NULL,
  CONSTRAINT "event_participations_attendance_status_check" CHECK (attendance_status IS NULL OR (attendance_status = ANY (ARRAY['attended'::text, 'absent_excused'::text, 'absent_unexcused'::text, 'registered_no_response'::text, 'walk_in'::text, 'unknown'::text, 'registered_absent'::text]))),
  CONSTRAINT "event_participations_pkey" PRIMARY KEY (id),
  CONSTRAINT "event_participations_registration_status_check" CHECK (registration_status IS NULL OR (registration_status = ANY (ARRAY['registered'::text, 'confirmed'::text, 'declined'::text, 'no_response'::text, 'cancelled'::text, 'unknown'::text]))),
  CONSTRAINT "event_participations_role_at_event_check" CHECK (role_at_event IS NULL OR (role_at_event = ANY (ARRAY['mentor'::text, 'mentee'::text, 'core_team'::text, 'speaker'::text, 'trainer'::text, 'guest'::text, 'unknown'::text])))
);

CREATE TABLE "public"."mentoring_recaps" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "season_id" uuid,
  "match_id" uuid,
  "mentor_person_id" uuid,
  "mentee_person_id" uuid,
  "meeting_date" date NOT NULL,
  "meeting_month" text NOT NULL,
  "recap_url" text NOT NULL,
  "recap_source" text DEFAULT 'facebook_group'::text NOT NULL,
  "recap_note" text,
  "issue_flag" boolean DEFAULT false NOT NULL,
  "status" text DEFAULT 'submitted'::text NOT NULL,
  "admin_notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "meeting_type" text DEFAULT '1on1_primary'::text NOT NULL,
  "captured_by" text,
  CONSTRAINT "mentoring_recaps_meeting_month_check" CHECK (meeting_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'::text),
  CONSTRAINT "mentoring_recaps_meeting_type_check" CHECK (meeting_type = ANY (ARRAY['1on1_primary'::text, '1on1_cross'::text, 'group'::text, 'online'::text, 'offline'::text, 'unknown'::text])),
  CONSTRAINT "mentoring_recaps_pkey" PRIMARY KEY (id),
  CONSTRAINT "mentoring_recaps_recap_source_check" CHECK (recap_source = ANY (ARRAY['facebook_group'::text, 'google_sheet'::text, 'admin_input'::text])),
  CONSTRAINT "mentoring_recaps_status_check" CHECK (status = ANY (ARRAY['submitted'::text, 'needs_review'::text, 'invalid'::text, 'duplicate'::text, 'deleted'::text, 'excluded'::text]))
);

CREATE TABLE "public"."season_monthly_kpis" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "season_id" uuid NOT NULL,
  "month_value" text NOT NULL,
  "closed" boolean DEFAULT false NOT NULL,
  "total_mentees" integer DEFAULT 0 NOT NULL,
  "total_recap_entries" integer DEFAULT 0 NOT NULL,
  "distinct_mentees_with_recap" integer DEFAULT 0 NOT NULL,
  "total_mentors" integer DEFAULT 0 NOT NULL,
  "pct_mentees_with_recap" numeric,
  "source_name" text,
  "source_file" text,
  "batch_id" uuid,
  "notes" text,
  "closed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "season_monthly_kpis_month_check" CHECK (month_value ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'::text),
  CONSTRAINT "season_monthly_kpis_pkey" PRIMARY KEY (id),
  CONSTRAINT "season_monthly_kpis_season_month_key" UNIQUE (season_id, month_value)
);

CREATE TABLE "public"."admin_users" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "auth_user_id" uuid,
  "email" text NOT NULL,
  "full_name" text,
  "role" text DEFAULT 'viewer'::text NOT NULL,
  "status" text DEFAULT 'active'::text NOT NULL,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "admin_users_email_key" UNIQUE (email),
  CONSTRAINT "admin_users_pkey" PRIMARY KEY (id),
  CONSTRAINT "admin_users_role_check" CHECK (role = ANY (ARRAY['viewer'::text, 'reviewer'::text, 'support_team'::text, 'core_team'::text, 'admin'::text, 'super_admin'::text])),
  CONSTRAINT "admin_users_status_check" CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'suspended'::text, 'inactive'::text]))
);

CREATE TABLE "public"."admin_scope_access" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "program_id" text,
  "season_id" text,
  "role" text,
  "created_at" timestamp without time zone DEFAULT now(),
  "status" text DEFAULT 'active'::text,
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "admin_scope_access_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."application_reviews" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "application_id" uuid NOT NULL,
  "review_round" text NOT NULL,
  "reviewer_admin_user_id" uuid,
  "reviewer_person_id" uuid,
  "assigned_by" uuid,
  "assigned_at" timestamp with time zone DEFAULT now(),
  "due_at" timestamp with time zone,
  "status" text DEFAULT 'assigned'::text NOT NULL,
  "score_motivation" integer,
  "score_goal_clarity" integer,
  "score_commitment" integer,
  "score_fit" integer,
  "score_communication" integer,
  "total_score" integer,
  "recommendation" text,
  "reviewer_note" text,
  "submitted_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "assignment_batch_id" uuid,
  "claimed_at" timestamp with time zone,
  "claim_source" text,
  CONSTRAINT "application_reviews_pkey" PRIMARY KEY (id),
  CONSTRAINT "application_reviews_recommendation_check" CHECK (recommendation IS NULL OR (recommendation = ANY (ARRAY['pass_to_interview'::text, 'waitlist'::text, 'reject'::text, 'needs_admin_review'::text, 'pass_orientation'::text, 'approve_recommended'::text]))),
  CONSTRAINT "application_reviews_review_round_check" CHECK (review_round = ANY (ARRAY['profile_screening'::text, 'interview'::text])),
  CONSTRAINT "application_reviews_score_commitment_check" CHECK (score_commitment IS NULL OR score_commitment >= 1 AND score_commitment <= 5),
  CONSTRAINT "application_reviews_score_communication_check" CHECK (score_communication IS NULL OR score_communication >= 1 AND score_communication <= 5),
  CONSTRAINT "application_reviews_score_fit_check" CHECK (score_fit IS NULL OR score_fit >= 1 AND score_fit <= 5),
  CONSTRAINT "application_reviews_score_goal_clarity_check" CHECK (score_goal_clarity IS NULL OR score_goal_clarity >= 1 AND score_goal_clarity <= 5),
  CONSTRAINT "application_reviews_score_motivation_check" CHECK (score_motivation IS NULL OR score_motivation >= 1 AND score_motivation <= 5),
  CONSTRAINT "application_reviews_status_check" CHECK (status = ANY (ARRAY['assigned'::text, 'in_progress'::text, 'submitted'::text, 'returned_for_clarification'::text, 'cancelled'::text]))
);

CREATE TABLE "public"."application_decisions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "application_id" uuid NOT NULL,
  "decided_by" uuid,
  "decided_by_name" text,
  "decision" text NOT NULL,
  "previous_status" text,
  "new_status" text NOT NULL,
  "decision_note" text,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "application_decisions_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."review_assignment_batches" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "intake_batch_id" uuid,
  "review_round" text DEFAULT 'profile_screening'::text NOT NULL,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "due_at" timestamp with time zone,
  "assignment_note" text,
  "application_count" integer,
  "reviewer_count" integer,
  CONSTRAINT "review_assignment_batches_pkey" PRIMARY KEY (id),
  CONSTRAINT "review_assignment_batches_round_check" CHECK (review_round = ANY (ARRAY['profile_screening'::text, 'interview'::text]))
);

CREATE TABLE "public"."person_season_memberships" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "person_id" uuid NOT NULL,
  "program_id" uuid NOT NULL,
  "season_id" uuid NOT NULL,
  "intake_batch_id" uuid,
  "role" text NOT NULL,
  "status" text DEFAULT 'active'::text NOT NULL,
  "source" text DEFAULT 'manual'::text NOT NULL,
  "start_date" date,
  "end_date" date,
  "notes" text,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "person_season_memberships_dates_check" CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CONSTRAINT "person_season_memberships_person_season_role_key" UNIQUE (person_id, season_id, role),
  CONSTRAINT "person_season_memberships_pkey" PRIMARY KEY (id),
  CONSTRAINT "person_season_memberships_role_check" CHECK (role = ANY (ARRAY['mentee'::text, 'mentor'::text, 'supporter'::text, 'reviewer'::text, 'interviewer'::text, 'coreteam'::text, 'advisor'::text, 'alumni_mentee'::text, 'guest'::text])),
  CONSTRAINT "person_season_memberships_source_check" CHECK (source = ANY (ARRAY['manual'::text, 'application'::text, 'profile'::text, 'match'::text, 'event'::text, 'backfill'::text, 'rollover'::text, 'system'::text])),
  CONSTRAINT "person_season_memberships_status_check" CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'paused'::text, 'withdrawn'::text, 'completed'::text, 'graduated'::text, 'opted_out'::text, 'cancelled'::text]))
);

CREATE TABLE "public"."person_season_membership_log" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "membership_id" uuid NOT NULL,
  "person_id" uuid NOT NULL,
  "program_id" uuid NOT NULL,
  "season_id" uuid NOT NULL,
  "role" text NOT NULL,
  "old_status" text,
  "new_status" text NOT NULL,
  "transition_type" text DEFAULT 'manual'::text NOT NULL,
  "reason" text,
  "changed_by" uuid,
  "changed_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "person_season_membership_log_new_status_check" CHECK (new_status = ANY (ARRAY['invited'::text, 'active'::text, 'paused'::text, 'withdrawn'::text, 'completed'::text, 'graduated'::text, 'opted_out'::text, 'cancelled'::text])),
  CONSTRAINT "person_season_membership_log_old_status_check" CHECK (old_status IS NULL OR (old_status = ANY (ARRAY['invited'::text, 'active'::text, 'paused'::text, 'withdrawn'::text, 'completed'::text, 'graduated'::text, 'opted_out'::text, 'cancelled'::text]))),
  CONSTRAINT "person_season_membership_log_pkey" PRIMARY KEY (id),
  CONSTRAINT "person_season_membership_log_role_check" CHECK (role = ANY (ARRAY['mentee'::text, 'mentor'::text, 'supporter'::text, 'reviewer'::text, 'interviewer'::text, 'coreteam'::text, 'advisor'::text, 'alumni_mentee'::text, 'guest'::text])),
  CONSTRAINT "person_season_membership_log_transition_type_check" CHECK (transition_type = ANY (ARRAY['created'::text, 'status_change'::text, 'role_change'::text, 'rollover'::text, 'backfill'::text, 'manual'::text, 'system'::text]))
);

-- BLOCKED TABLE: public.matches
-- Exact catalog metadata lacks numeric typmod for match_confidence and no repository creation/alteration source resolves it.
-- No CREATE TABLE is emitted. Dependent constraints remain blocked.
