-- STAGING ONLY. DESIGN ONLY. NOT AUTHORIZED. NOT EXECUTED.
-- MUST NEVER RUN ON PRODUCTION.
-- OWNER APPROVAL REQUIRED: table-by-table RLS/policy choices are documented in
-- docs/audits/VAM_OS_STAGING_RLS_AND_GRANTS_TARGET_2026-07-22.md.
-- No production policy is copied blindly. No policy DDL is emitted before approval.
-- Migration 061 security remains outside this pre-061 baseline.
