begin;

do $$
declare v_missing text; v_unexpected text;
begin
  select string_agg(x,', ') into v_missing from unnest(array[
    'public.admin_users','public.admin_scope_access','public.admin_audit_log','public.people','public.programs','public.seasons','public.intake_batches','public.person_season_memberships','public.person_season_membership_log'
  ]) x where to_regclass(x) is null;
  if v_missing is not null then raise exception 'VAM062 prerequisite tables missing: %',v_missing; end if;
  if to_regnamespace('auth') is null or to_regprocedure('gen_random_uuid()') is null then raise exception 'VAM062 required schema/function missing'; end if;
  if to_regprocedure('public.current_admin_role()') is null or to_regprocedure('public.is_active_admin()') is null then raise exception 'VAM062 admin helpers missing'; end if;
  if exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth') and c.relname in ('admin_users','admin_scope_access','admin_audit_log','people','programs','seasons','intake_batches','person_season_memberships','person_season_membership_log') and pg_get_userbyid(c.relowner)<>current_user) then raise exception 'VAM062 ownership mismatch'; end if;
  if exists(select 1 from information_schema.columns c where c.table_schema='public' and ((c.table_name='admin_users' and c.column_name in ('id','auth_user_id') and c.udt_name<>'uuid') or (c.table_name='person_season_memberships' and c.column_name in ('id','person_id','program_id','season_id','intake_batch_id') and c.udt_name<>'uuid') or c.is_identity='YES' or c.is_generated<>'NEVER')) then raise exception 'VAM062 column type or generation mismatch'; end if;
  if not exists(select 1 from pg_constraint where conrelid='public.seasons'::regclass and contype='f' and pg_get_constraintdef(oid)='FOREIGN KEY (program_id) REFERENCES programs(id)') then raise exception 'VAM062 season-program relationship mismatch'; end if;
  if not exists(select 1 from pg_constraint where conrelid='public.intake_batches'::regclass and contype='f' and pg_get_constraintdef(oid)='FOREIGN KEY (season_id) REFERENCES seasons(id)') then raise exception 'VAM062 batch-season relationship mismatch'; end if;
  if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('current_admin_role','is_active_admin') and (p.prosecdef is false or p.provolatile<>'s' or pg_get_userbyid(p.proowner)<>current_user)) then raise exception 'VAM062 helper definition or ownership mismatch'; end if;
  if has_function_privilege('anon','public.current_admin_role()','execute') or not has_function_privilege('authenticated','public.current_admin_role()','execute') then raise exception 'VAM062 helper privilege mismatch'; end if;
  if exists(select 1 from information_schema.columns c where c.table_schema='public' and c.table_name='admin_users' and c.column_name in ('id','auth_user_id','email','full_name','role','status') having count(*)<>6) then raise exception 'VAM062 admin_users columns incompatible'; end if;
  if exists(select 1 from information_schema.columns c where c.table_schema='public' and c.table_name='person_season_memberships' and c.column_name in ('id','person_id','program_id','season_id','intake_batch_id','role','status','source','created_by') having count(*)<>9) then raise exception 'VAM062 membership columns incompatible'; end if;
  if to_regclass('public.account_rls_package_state') is not null or to_regclass('public.account_rls_package_manifest') is not null or to_regclass('public.account_import_batches') is not null or to_regclass('public.account_import_outcomes') is not null or to_regclass('public.account_auth_reconciliation') is not null or to_regclass('public.account_import_previews') is not null then raise exception 'VAM062 package table name collision'; end if;
  if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'vam062_%') then raise exception 'VAM062 package function name collision'; end if;
  select string_agg(tablename||'.'||policyname,', ') into v_unexpected from pg_policies where schemaname='public' and tablename in ('admin_users','admin_scope_access','admin_audit_log','people','person_season_memberships') and not (
   tablename='admin_users' and policyname='read_admin_users_super_admin_or_self' and permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and qual='((auth.uid() = auth_user_id) OR (current_admin_role() = ''super_admin''::text))' or
   tablename='admin_scope_access' and policyname='read_admin_scope_access_self_or_super_admin' and permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and qual='((current_admin_role() = ''super_admin''::text) OR (is_active_admin() AND (user_id = auth.uid()) AND (status = ''active''::text)))' or
   tablename='admin_audit_log' and policyname='read_admin_audit_log_super_admin_only' and permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and qual='(current_admin_role() = ''super_admin''::text)');
  if v_unexpected is not null then raise exception 'VAM062 unexpected existing policies: %',v_unexpected; end if;
  if not exists(select 1 from pg_constraint c join pg_index i on i.indexrelid=c.conindid where c.conrelid='public.admin_users'::regclass and c.contype in ('u','x') and c.convalidated and pg_get_constraintdef(c.oid,true)='UNIQUE (email)' and i.indpred is null and i.indexprs is null and not i.indisnullsnotdistinct) then raise exception 'VAM062 admin_users(email) conflict target missing or incompatible'; end if;
  if not exists(select 1 from pg_constraint c join pg_index i on i.indexrelid=c.conindid where c.conrelid='public.admin_scope_access'::regclass and c.contype in ('u','x') and c.convalidated and pg_get_constraintdef(c.oid,true)='UNIQUE (user_id, program_id, season_id)' and i.indpred is null and i.indexprs is null and not i.indisnullsnotdistinct) then raise exception 'VAM062 admin_scope_access conflict target missing or incompatible'; end if;
  if not exists(select 1 from pg_constraint c join pg_index i on i.indexrelid=c.conindid where c.conrelid='public.person_season_memberships'::regclass and c.contype in ('u','x') and c.convalidated and pg_get_constraintdef(c.oid,true)='UNIQUE (person_id, season_id, role)' and i.indpred is null and i.indexprs is null and not i.indisnullsnotdistinct) then raise exception 'VAM062 membership conflict target missing or incompatible'; end if;  if not exists(select 1 from pg_constraint c where c.conrelid='public.admin_users'::regclass and c.contype='c' and pg_get_constraintdef(c.oid) ilike '%invited%' and pg_get_constraintdef(c.oid) ilike '%active%' and pg_get_constraintdef(c.oid) ilike '%suspended%' and pg_get_constraintdef(c.oid) ilike '%inactive%') then raise exception 'VAM062 account lifecycle constraint mismatch'; end if;
  if not exists(select 1 from pg_constraint c where c.conrelid='public.person_season_memberships'::regclass and c.contype='c' and pg_get_constraintdef(c.oid) ilike '%mentor%' and pg_get_constraintdef(c.oid) ilike '%mentee%' and pg_get_constraintdef(c.oid) ilike '%invited%') then raise exception 'VAM062 membership lifecycle constraint mismatch'; end if;
end $$;

create table public.account_rls_package_state(table_name text primary key check(table_name in ('admin_users','admin_scope_access','admin_audit_log','people','person_season_memberships')),rls_was_enabled boolean not null,rls_was_forced boolean not null,package_version text not null check(package_version='VAM062_V3'),state_checksum text not null,recorded_at timestamptz not null default transaction_timestamp());
insert into public.account_rls_package_state
select c.relname,c.relrowsecurity,c.relforcerowsecurity,'VAM062_V3',encode(digest('VAM062_V3|'||c.relname||'|'||c.relrowsecurity||'|'||c.relforcerowsecurity,'sha256'),'hex'),transaction_timestamp() from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('admin_users','admin_scope_access','admin_audit_log','people','person_season_memberships');
do $$ begin if (select count(*) from public.account_rls_package_state)<>5 then raise exception 'VAM062 incomplete RLS state capture'; end if; end $$;

create table public.account_import_batches(id uuid primary key default gen_random_uuid(),actor_admin_user_id uuid not null references public.admin_users(id),source_sha256 text not null check(source_sha256~'^[0-9a-f]{64}$'),row_count integer not null check(row_count between 1 and 500),status text not null check(status in ('processing','completed','completed_with_errors')),created_at timestamptz not null default now(),completed_at timestamptz);
create table public.account_import_outcomes(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.account_import_batches(id) on delete cascade,row_number integer not null check(row_number>=2),outcome_status text not null check(outcome_status in ('created','updated','skipped','failed')),reason_code text not null check(length(reason_code) between 1 and 240),auth_user_id_hash text null check(auth_user_id_hash is null or auth_user_id_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default now(),unique(batch_id,row_number));
create table public.account_auth_reconciliation(operation_id uuid primary key,identifier_hash text not null check(identifier_hash~'^[0-9a-f]{64}$'),action_type text not null,failure_class text not null,retry_status text not null default 'required' check(retry_status in ('required','in_progress','resolved')),correlation_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.account_import_previews(id uuid primary key,actor_admin_user_id uuid not null references public.admin_users(id),secret_hash text not null check(secret_hash~'^[0-9a-f]{64}$'),ciphertext text not null,iv text not null,auth_tag text not null,expires_at timestamptz not null,created_at timestamptz not null default now());

create function public.vam062_current_admin_id() returns uuid language sql stable security definer set search_path=public as $$select id from public.admin_users where auth_user_id=auth.uid() and status='active' limit 1$$;
create function public.vam062_admin_mutation_atomic(p_actor_admin_user_id uuid,p_operation text,p_target_admin_user_id uuid,p_payload jsonb) returns void language plpgsql security definer set search_path=public as $$
declare v_target uuid; v_auth uuid; v_before jsonb; v_after jsonb; v_action text;
begin
 if not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') then raise exception 'VAM062 unauthorized actor'; end if;
 if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' then raise exception 'VAM062 trusted server context required'; end if;
 if p_operation in ('upsert','update','link_auth') and not exists(select 1 from public.programs p join public.seasons s on s.program_id=p.id where p.is_active and (p.id::text=p_payload->>'program_id' or p.code=p_payload->>'program_id') and (s.id::text=p_payload->>'season_id' or s.code=p_payload->>'season_id')) then raise exception 'VAM062 invalid program-season relationship'; end if;
 if p_operation='upsert' then
   if p_payload->>'role' not in ('viewer','reviewer','support_team','core_team','admin','super_admin') then raise exception 'VAM062 invalid role'; end if;
   select id,to_jsonb(a) into v_target,v_before from public.admin_users a where email=lower(btrim(p_payload->>'email'));
   insert into public.admin_users(auth_user_id,email,full_name,role,status) values((p_payload->>'auth_user_id')::uuid,lower(btrim(p_payload->>'email')),nullif(btrim(p_payload->>'full_name'),''),p_payload->>'role',p_payload->>'status') on conflict(email) do update set auth_user_id=excluded.auth_user_id,full_name=excluded.full_name,role=excluded.role,status=excluded.status returning id,auth_user_id into v_target,v_auth;
   if nullif(p_payload->>'season_id','') is null then raise exception 'VAM062 explicit season required'; end if;
   insert into public.admin_scope_access(user_id,program_id,season_id,role,status) values(v_auth,p_payload->>'program_id',p_payload->>'season_id',p_payload->>'scope_role',p_payload->>'scope_status') on conflict(user_id,program_id,season_id) do update set role=excluded.role,status=excluded.status;
   v_action:=case when v_before is null then 'create_admin_user' else 'update_admin_user' end;
 elsif p_operation='update' then
   select to_jsonb(a),auth_user_id into v_before,v_auth from public.admin_users a where id=p_target_admin_user_id for update; if v_before is null then raise exception 'VAM062 target missing'; end if;
   update public.admin_users set full_name=nullif(btrim(p_payload->>'full_name'),''),role=p_payload->>'role',status=p_payload->>'status' where id=p_target_admin_user_id returning id into v_target;
   if nullif(p_payload->>'season_id','') is null then raise exception 'VAM062 explicit season required'; end if;
   if nullif(p_payload->>'scope_id','') is not null then update public.admin_scope_access set program_id=p_payload->>'program_id',season_id=p_payload->>'season_id',role=p_payload->>'scope_role',status=p_payload->>'scope_status' where id=(p_payload->>'scope_id')::uuid and user_id=v_auth; if not found then raise exception 'VAM062 scope mismatch'; end if; else insert into public.admin_scope_access(user_id,program_id,season_id,role,status) values(v_auth,p_payload->>'program_id',p_payload->>'season_id',p_payload->>'scope_role',p_payload->>'scope_status') on conflict(user_id,program_id,season_id) do update set role=excluded.role,status=excluded.status; end if;
   v_action:='update_admin_user';
 elsif p_operation='link_auth' then
   select to_jsonb(a) into v_before from public.admin_users a where id=p_target_admin_user_id for update; if v_before is null then raise exception 'VAM062 target missing'; end if;
   update public.admin_users set auth_user_id=(p_payload->>'auth_user_id')::uuid where id=p_target_admin_user_id returning id,auth_user_id into v_target,v_auth;
   if nullif(p_payload->>'season_id','') is null then raise exception 'VAM062 explicit season required'; end if;
   insert into public.admin_scope_access(user_id,program_id,season_id,role,status) values(v_auth,p_payload->>'program_id',p_payload->>'season_id',p_payload->>'scope_role',p_payload->>'scope_status') on conflict(user_id,program_id,season_id) do update set role=excluded.role,status=excluded.status;
   v_action:='sync_auth';
 elsif p_operation in ('status','remove') then
   select to_jsonb(a),auth_user_id into v_before,v_auth from public.admin_users a where id=p_target_admin_user_id for update; if v_before is null then raise exception 'VAM062 target missing'; end if;
   update public.admin_users set status=case when p_operation='remove' then 'inactive' else p_payload->>'status' end where id=p_target_admin_user_id returning id into v_target;
   update public.admin_scope_access set status=case when p_operation='status' and p_payload->>'status'='active' then 'active' else 'inactive' end where user_id=v_auth;
   v_action:=case when p_operation='remove' then 'remove_admin_access' when p_payload->>'status'='active' then 'reactivate_admin_user' else 'deactivate_admin_user' end;
 else raise exception 'VAM062 unsupported operation'; end if;
 select to_jsonb(a) into v_after from public.admin_users a where id=v_target;
 insert into public.admin_audit_log(actor_admin_user_id,action_type,target_admin_user_id,before_data,after_data) values(p_actor_admin_user_id,v_action,v_target,v_before,v_after);
end $$;

create function public.vam062_upsert_staff_account_atomic(p_actor_admin_user_id uuid,p_batch_id uuid,p_row_number integer,p_auth_user_id uuid,p_email text,p_display_name text,p_role text,p_program_id uuid,p_season_id uuid,p_scope_role text) returns void language plpgsql security definer set search_path=public as $$
declare v_target uuid; v_existing boolean;
begin
 if not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') then raise exception 'VAM062 unauthorized actor'; end if;
 if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' then raise exception 'VAM062 trusted server context required'; end if;
 if not exists(select 1 from public.programs p join public.seasons s on s.program_id=p.id where p.id=p_program_id and p.is_active and s.id=p_season_id) then raise exception 'VAM062 invalid active program-season relationship'; end if;
 if p_role not in ('viewer','reviewer','support_team','core_team','admin') then raise exception 'VAM062 unsupported staff role'; end if;
 select exists(select 1 from public.admin_users where email=lower(btrim(p_email))) into v_existing;
 insert into public.admin_users(auth_user_id,email,full_name,role,status) values(p_auth_user_id,lower(btrim(p_email)),nullif(btrim(p_display_name),''),p_role,'invited') on conflict(email) do update set auth_user_id=excluded.auth_user_id,full_name=excluded.full_name,role=excluded.role returning id into v_target;
 insert into public.admin_scope_access(user_id,program_id,season_id,role,status) values(p_auth_user_id,p_program_id::text,p_season_id::text,p_scope_role,'inactive') on conflict(user_id,program_id,season_id) do update set role=excluded.role,status=excluded.status;
 if not exists(select 1 from public.admin_scope_access where user_id=p_auth_user_id and program_id=p_program_id::text and season_id=p_season_id::text and role=p_scope_role and status='inactive') then raise exception 'VAM062 scope reconciliation failed'; end if;
 insert into public.admin_audit_log(actor_admin_user_id,action_type,target_admin_user_id,before_data,after_data) values(p_actor_admin_user_id,case when v_existing then 'update_admin_user' else 'create_admin_user' end,v_target,null,jsonb_build_object('program_id',p_program_id,'season_id',p_season_id,'role',p_role,'status','invited'));
 insert into public.account_import_outcomes(batch_id,row_number,outcome_status,reason_code) values(p_batch_id,p_row_number,case when v_existing then 'updated' else 'created' end,case when v_existing then 'staff_account_updated' else 'staff_account_invited' end);
end $$;

create function public.vam062_import_participant_membership_atomic(p_actor_admin_user_id uuid,p_batch_id uuid,p_row_number integer,p_email text,p_display_name text,p_role text,p_program_id uuid,p_season_id uuid,p_intake_batch_id uuid) returns table(outcome_status text,reason_code text) language plpgsql security definer set search_path=public as $$
declare v_person uuid; v_membership uuid; v_existing boolean; v_old_status text;
begin
 if not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') then raise exception 'VAM062 unauthorized actor'; end if;
 if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' then raise exception 'VAM062 trusted server context required'; end if;
 if not exists(select 1 from public.programs p join public.seasons s on s.program_id=p.id left join public.intake_batches b on b.season_id=s.id where p.id=p_program_id and p.is_active and s.id=p_season_id and (p_intake_batch_id is null or b.id=p_intake_batch_id)) then raise exception 'VAM062 invalid program-season-batch relationship'; end if;
 if p_role not in ('mentor','mentee') then raise exception 'VAM062 unsupported participant role'; end if;
 select id into v_person from public.people where email_primary=lower(btrim(p_email));
 if v_person is null then insert into public.people(email_primary,full_name) values(lower(btrim(p_email)),btrim(p_display_name)) returning id into v_person; end if;
 select id,status into v_membership,v_old_status from public.person_season_memberships where person_id=v_person and season_id=p_season_id and role=p_role;
 v_existing:=v_membership is not null;
 if v_existing and v_old_status='invited' and coalesce((select intake_batch_id from public.person_season_memberships where id=v_membership),'00000000-0000-0000-0000-000000000000'::uuid)=coalesce(p_intake_batch_id,'00000000-0000-0000-0000-000000000000'::uuid) then
   insert into public.account_import_outcomes(batch_id,row_number,outcome_status,reason_code) values(p_batch_id,p_row_number,'skipped','membership_already_current'); return query select 'skipped','membership_already_current'; return;
 end if;
 if v_existing and exists(select 1 from public.person_season_memberships where id=v_membership and program_id<>p_program_id) then raise exception 'VAM062 cross-program reassignment denied'; end if;
 insert into public.person_season_memberships(person_id,program_id,season_id,intake_batch_id,role,status,source,created_by) values(v_person,p_program_id,p_season_id,p_intake_batch_id,p_role,'invited','manual',p_actor_admin_user_id) on conflict(person_id,season_id,role) do update set program_id=excluded.program_id,intake_batch_id=excluded.intake_batch_id,status='invited' returning id into v_membership;
 insert into public.person_season_membership_log(membership_id,person_id,program_id,season_id,role,old_status,new_status,transition_type,reason,changed_by) values(v_membership,v_person,p_program_id,p_season_id,p_role,v_old_status,'invited',case when v_existing then 'status_change' else 'created' end,'account_csv_import',p_actor_admin_user_id);
 insert into public.admin_audit_log(actor_admin_user_id,action_type,before_data,after_data) values(p_actor_admin_user_id,'import_participant_membership',null,jsonb_build_object('operation','participant_membership_import','program_id',p_program_id,'season_id',p_season_id,'role',p_role,'participant_auth_created',false));
 insert into public.account_import_outcomes(batch_id,row_number,outcome_status,reason_code) values(p_batch_id,p_row_number,case when v_existing then 'updated' else 'created' end,case when v_existing then 'membership_updated' else 'membership_created_no_auth' end);
 return query select case when v_existing then 'updated' else 'created' end,case when v_existing then 'membership_updated' else 'membership_created_no_auth' end;
end $$;

create function public.vam062_record_reconciliation(p_actor_admin_user_id uuid,p_batch_id uuid,p_row_number integer,p_auth_user_id_hash text) returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') then raise exception 'VAM062 unauthorized actor'; end if; insert into public.account_import_outcomes(batch_id,row_number,outcome_status,reason_code,auth_user_id_hash) values(p_batch_id,p_row_number,'failed','reconciliation_required',p_auth_user_id_hash) on conflict(batch_id,row_number) do update set outcome_status='failed',reason_code='reconciliation_required',auth_user_id_hash=excluded.auth_user_id_hash; end$$;
create function public.vam062_record_auth_reconciliation(p_actor_admin_user_id uuid,p_operation_id uuid,p_identifier_hash text,p_action_type text,p_failure_class text,p_retry_status text,p_correlation_metadata jsonb) returns void language plpgsql security definer set search_path=public as $$begin if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' or not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') or p_retry_status not in ('required','resolved') then raise exception 'VAM062 reconciliation rejected'; end if; insert into public.account_auth_reconciliation(operation_id,identifier_hash,action_type,failure_class,retry_status,correlation_metadata) values(p_operation_id,p_identifier_hash,p_action_type,p_failure_class,p_retry_status,coalesce(p_correlation_metadata,'{}')); end$$;
create function public.vam062_create_account_preview(p_preview_id uuid,p_actor_admin_user_id uuid,p_secret_hash text,p_ciphertext text,p_iv text,p_auth_tag text,p_expires_at timestamptz,p_max_previews integer) returns void language plpgsql security definer set search_path=public as $$begin if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' or not exists(select 1 from public.admin_users where id=p_actor_admin_user_id and role='super_admin' and status='active') or p_expires_at<=now() or p_expires_at>now()+interval '10 minutes' or p_max_previews<>50 then raise exception 'VAM062 preview rejected';end if;perform pg_advisory_xact_lock(hashtext('VAM062_PREVIEW_STORE'));delete from public.account_import_previews where expires_at<=now();if(select count(*) from public.account_import_previews)>=p_max_previews then raise exception 'VAM062 preview capacity reached';end if;insert into public.account_import_previews values(p_preview_id,p_actor_admin_user_id,p_secret_hash,p_ciphertext,p_iv,p_auth_tag,p_expires_at,now());end$$;
create function public.vam062_consume_account_preview(p_preview_id uuid,p_actor_admin_user_id uuid,p_secret_hash text) returns table(ciphertext text,iv text,auth_tag text) language sql security definer set search_path=public as $$delete from public.account_import_previews where id=p_preview_id and actor_admin_user_id=p_actor_admin_user_id and secret_hash=p_secret_hash and expires_at>now() returning ciphertext,iv,auth_tag$$;
create table public.account_rls_package_manifest(object_kind text not null,object_name text not null,table_name text,definition_hash text not null,owner_name text not null,primary key(object_kind,object_name));
insert into public.account_rls_package_manifest select 'function',p.proname,null,md5(regexp_replace(pg_get_functiondef(p.oid),'\s+',' ','g')),pg_get_userbyid(p.proowner) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'vam062_%';

alter table public.admin_users enable row level security; alter table public.admin_scope_access enable row level security; alter table public.admin_audit_log enable row level security; alter table public.people enable row level security; alter table public.person_season_memberships enable row level security; alter table public.account_import_batches enable row level security; alter table public.account_import_outcomes enable row level security; alter table public.account_auth_reconciliation enable row level security; alter table public.account_import_previews enable row level security;
create policy vam062_admin_users_self_or_super on public.admin_users for select to authenticated using(auth_user_id=auth.uid() or public.current_admin_role()='super_admin');
create policy vam062_scope_self_or_super on public.admin_scope_access for select to authenticated using(user_id=auth.uid() or public.current_admin_role()='super_admin');
create policy vam062_audit_actor_or_super on public.admin_audit_log for select to authenticated using(actor_admin_user_id=public.vam062_current_admin_id() or public.current_admin_role()='super_admin');
create policy vam062_people_program_ops on public.people for select to authenticated using(public.current_admin_role()='super_admin' or exists(select 1 from public.person_season_memberships m join public.admin_scope_access s on s.user_id=auth.uid() and s.status='active' and s.role in ('full_access','operations') and s.program_id=m.program_id::text and s.season_id is not null and s.season_id=m.season_id::text where m.person_id=people.id));
create policy vam062_membership_program_ops on public.person_season_memberships for select to authenticated using(public.current_admin_role()='super_admin' or exists(select 1 from public.admin_scope_access s where s.user_id=auth.uid() and s.status='active' and s.role in ('full_access','operations') and s.program_id=person_season_memberships.program_id::text and s.season_id is not null and s.season_id=person_season_memberships.season_id::text));
insert into public.account_rls_package_manifest select 'policy',policyname,tablename,md5(concat_ws('|',tablename,policyname,permissive,array_to_string(roles,','),cmd,coalesce(qual,''),coalesce(with_check,''))),current_user from pg_policies where schemaname='public' and policyname like 'vam062_%';

revoke all on public.account_rls_package_state,public.account_rls_package_manifest,public.account_import_batches,public.account_import_outcomes,public.account_auth_reconciliation,public.account_import_previews from public,anon,authenticated;
revoke all on function public.vam062_current_admin_id(),public.vam062_admin_mutation_atomic(uuid,text,uuid,jsonb),public.vam062_upsert_staff_account_atomic(uuid,uuid,integer,uuid,text,text,text,uuid,uuid,text),public.vam062_import_participant_membership_atomic(uuid,uuid,integer,text,text,text,uuid,uuid,uuid),public.vam062_record_reconciliation(uuid,uuid,integer,text),public.vam062_record_auth_reconciliation(uuid,uuid,text,text,text,text,jsonb),public.vam062_create_account_preview(uuid,uuid,text,text,text,text,timestamptz,integer),public.vam062_consume_account_preview(uuid,uuid,text) from public,anon,authenticated;
revoke all on public.account_rls_package_state from service_role;
revoke all on public.account_rls_package_manifest from service_role;
grant all on public.account_import_batches,public.account_import_outcomes,public.account_auth_reconciliation,public.account_import_previews to service_role;
grant execute on function public.vam062_current_admin_id(),public.vam062_admin_mutation_atomic(uuid,text,uuid,jsonb),public.vam062_upsert_staff_account_atomic(uuid,uuid,integer,uuid,text,text,text,uuid,uuid,text),public.vam062_import_participant_membership_atomic(uuid,uuid,integer,text,text,text,uuid,uuid,uuid),public.vam062_record_reconciliation(uuid,uuid,integer,text),public.vam062_record_auth_reconciliation(uuid,uuid,text,text,text,text,jsonb),public.vam062_create_account_preview(uuid,uuid,text,text,text,text,timestamptz,integer),public.vam062_consume_account_preview(uuid,uuid,text) to service_role;
commit;
