-- VAM062_V3 read-only verification. Missing evidence is FAIL.
with expected_policy(t,n,season_strict) as(values('admin_users','vam062_admin_users_self_or_super',false),('admin_scope_access','vam062_scope_self_or_super',false),('admin_audit_log','vam062_audit_actor_or_super',false),('people','vam062_people_program_ops',true),('person_season_memberships','vam062_membership_program_ops',true)),
actual_policy as(select tablename,policyname,permissive,roles,cmd,qual,with_check from pg_policies where schemaname='public'),
policy_assert as(select e.t,e.n,case when a.policyname is null then 'FAIL' when a.permissive<>'PERMISSIVE' or a.roles<>array['authenticated'] or a.cmd<>'SELECT' or a.with_check is not null then 'FAIL' when e.season_strict and (a.qual not like '%season_id IS NOT NULL%' or a.qual like '%season_id IS NULL%') then 'FAIL' else 'PASS' end status from expected_policy e left join actual_policy a on a.tablename=e.t and a.policyname=e.n),
expected_table(t)as(values('admin_users'),('admin_scope_access'),('admin_audit_log'),('people'),('person_season_memberships'),('account_import_batches'),('account_import_outcomes'),('account_auth_reconciliation'),('account_import_previews')),
rls_assert as(select e.t,case when c.relrowsecurity then 'PASS' else 'FAIL' end status,c.relforcerowsecurity forced from expected_table e left join pg_class c on c.oid=to_regclass('public.'||e.t)),
function_assert as(select case when count(*)=8 and bool_and(not has_function_privilege('anon',p.oid,'execute') and not has_function_privilege('authenticated',p.oid,'execute') and has_function_privilege('service_role',p.oid,'execute')) then 'PASS' else 'FAIL' end status from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'vam062_%'),
grant_assert as(select case when bool_and(not has_table_privilege('anon','public.'||t,'SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('authenticated','public.'||t,'SELECT,INSERT,UPDATE,DELETE')) then 'PASS' else 'FAIL' end status from(values('account_import_batches'),('account_import_outcomes'),('account_auth_reconciliation'),('account_import_previews'),('account_rls_package_state'))v(t)),
unexpected as(select a.tablename,a.policyname from actual_policy a where a.tablename in(select t from expected_table) and not exists(select 1 from expected_policy e where e.t=a.tablename and e.n=a.policyname) and a.policyname not in('read_admin_users_super_admin_or_self','read_admin_scope_access_self_or_super_admin','read_admin_audit_log_super_admin_only')),
baseline_assert as(select case when exists(select 1 from actual_policy where policyname='read_admin_users_super_admin_or_self' and not(permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and lower(regexp_replace(regexp_replace(qual,'::text','','g'),'[[:space:]()]','','g'))='auth.uid=auth_user_idorcurrent_admin_role=''super_admin''')) or exists(select 1 from actual_policy where policyname='read_admin_scope_access_self_or_super_admin' and not(permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and lower(regexp_replace(regexp_replace(qual,'::text','','g'),'[[:space:]()]','','g'))='current_admin_role=''super_admin''oris_active_adminanduser_id=auth.uidandstatus=''active''')) or exists(select 1 from actual_policy where policyname='read_admin_audit_log_super_admin_only' and not(permissive='PERMISSIVE' and roles=array['public'] and cmd='SELECT' and with_check is null and lower(regexp_replace(regexp_replace(qual,'::text','','g'),'[[:space:]()]','','g'))='current_admin_role=''super_admin''')) then 'FAIL' else 'PASS' end status),
manifest_assert as(select case when to_regclass('public.account_rls_package_manifest') is null then 'FAIL' when (select count(*) from public.account_rls_package_manifest)<>13 then 'FAIL' when exists(select 1 from public.account_rls_package_manifest m left join pg_proc p on m.object_kind='function' and p.proname=m.object_name left join pg_namespace n on n.oid=p.pronamespace and n.nspname='public' where m.object_kind='function' and (p.oid is null or m.owner_name<>pg_get_userbyid(p.proowner) or m.definition_hash<>md5(regexp_replace(pg_get_functiondef(p.oid),'\s+',' ','g')))) then 'FAIL' when exists(select 1 from public.account_rls_package_manifest m left join pg_policies p on m.object_kind='policy' and p.schemaname='public' and p.tablename=m.table_name and p.policyname=m.object_name where m.object_kind='policy' and (p.policyname is null or m.definition_hash<>md5(concat_ws('|',p.tablename,p.policyname,p.permissive,array_to_string(p.roles,','),p.cmd,coalesce(p.qual,''),coalesce(p.with_check,''))))) then 'FAIL' else 'PASS' end status)
select jsonb_build_object('package','VAM062_V3','policy_assertions',(select jsonb_agg(to_jsonb(x))from policy_assert x),'baseline_policy_exact',(select status from baseline_assert),'rls_assertions',(select jsonb_agg(to_jsonb(x))from rls_assert x),'package_functions_service_only',(select status from function_assert),'ordinary_dml_denied',(select status from grant_assert),'manifest_provenance',(select status from manifest_assert),'unexpected_policies',(select coalesce(jsonb_agg(to_jsonb(x)),'[]')from unexpected x),'null_season_denied',case when not exists(select 1 from policy_assert where status='FAIL' and n in('vam062_people_program_ops','vam062_membership_program_ops')) then 'PASS' else 'FAIL' end,'overall_status',case when exists(select 1 from policy_assert where status='FAIL') or (select status from baseline_assert)='FAIL' or exists(select 1 from rls_assert where status='FAIL') or (select status from function_assert)='FAIL' or (select status from grant_assert)='FAIL' or (select status from manifest_assert)='FAIL' or exists(select 1 from unexpected) then 'FAIL' else 'PASS' end) account_rls_post_apply_v3;
