import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { executeStaffMutation } from "@/lib/account-mutation-orchestrator";

vi.mock("server-only",()=>({}));
const read=(path:string)=>readFileSync(path,"utf8");

describe("mandatory audit and atomic mutation remediation",()=>{
  it("removes unreachable audit handling and makes the real writer throw a typed sanitized error",()=>{const source=read("lib/admin-users.ts");expect(source).not.toMatch(/return \{ data: \[\], error:[\s\S]*?\};\s*throw/);const writer=source.slice(source.indexOf("async function writeAuditLog"),source.indexOf("async function wouldRemove"));expect(writer).toContain('auditError.name = "MandatoryAuditError"');expect(writer).toContain("throw auditError");expect(writer).not.toContain("error.message)`");});
  it("uses one participant RPC for person, membership, outcome and audits",()=>{const source=read("lib/account-import-server.ts");const participant=source.slice(source.indexOf("async function upsertParticipantMembership"),source.indexOf("async function findAuthUser"));expect(participant).toContain('rpc("vam062_import_participant_membership_atomic"');expect(participant).not.toMatch(/\.from\("people"\)|\.from\("person_season_memberships"\)/);});
  it("compensates a new Auth identity when the database transaction fails",async()=>{const compensate=vi.fn();const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:"synthetic-id",ownership:"created"}),commitDatabase:async()=>{throw Error()},compensateAuth:compensate,recordCompensation:vi.fn(),recordReconciliation:vi.fn(),hashIdentifier:()=>"hash"});expect(result.reason).toBe("database_transaction_failed_auth_compensated");expect(compensate).toHaveBeenCalledOnce();});
  it("records reconciliation and never deletes when invite ownership is ambiguous",async()=>{const reconcile=vi.fn(),compensate=vi.fn(),commit=vi.fn();const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:null,ownership:"ambiguous"}),commitDatabase:commit,compensateAuth:compensate,recordCompensation:vi.fn(),recordReconciliation:reconcile,hashIdentifier:()=>"sanitized-hash"});expect(result.reason).toBe("ambiguous_auth_ownership_recorded");expect(reconcile).toHaveBeenCalledWith("sanitized-hash");expect(commit).not.toHaveBeenCalled();expect(compensate).not.toHaveBeenCalled();});
  it("does not delete a pre-existing Auth identity after database failure",async()=>{const compensate=vi.fn();const result=await executeStaffMutation({findAuth:async()=>({id:"existing"}),inviteAuth:vi.fn(),commitDatabase:async()=>{throw Error()},compensateAuth:compensate,recordCompensation:vi.fn(),recordReconciliation:vi.fn(),hashIdentifier:()=>"hash"});expect(result.reason).toBe("database_transaction_failed_no_new_auth");expect(compensate).not.toHaveBeenCalled();});
  it("fails closed with durable reconciliation required when compensation fails",async()=>{const reconcile=vi.fn();const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:"synthetic-id",ownership:"created"}),commitDatabase:async()=>{throw Error()},compensateAuth:async()=>{throw Error()},recordCompensation:vi.fn(),recordReconciliation:reconcile,hashIdentifier:()=>"non-secret-hash"});expect(result).toMatchObject({ok:false,status:"failed",reason:"reconciliation_required_recorded",reconciliationRequired:true});expect(reconcile).toHaveBeenCalledWith("non-secret-hash");});
  it("distinguishes failure to durably record reconciliation",async()=>{const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:"synthetic-id",ownership:"created"}),commitDatabase:async()=>{throw Error()},compensateAuth:async()=>{throw Error()},recordCompensation:vi.fn(),recordReconciliation:async()=>{throw Error()},hashIdentifier:()=>"hash"});expect(result.reason).toBe("critical_reconciliation_recording_failed")});
  it("distinguishes failure to record successful compensation",async()=>{const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:"synthetic-id",ownership:"created"}),commitDatabase:async()=>{throw Error()},compensateAuth:async()=>{},recordCompensation:async()=>{throw Error()},recordReconciliation:vi.fn(),hashIdentifier:()=>"hash"});expect(result.reason).toBe("critical_compensation_recording_failed")});
  it("reports success only after the database transaction succeeds",async()=>{const result=await executeStaffMutation({findAuth:async()=>null,inviteAuth:async()=>({id:"synthetic-id",ownership:"created"}),commitDatabase:async()=>{},compensateAuth:vi.fn(),recordCompensation:vi.fn(),recordReconciliation:vi.fn(),hashIdentifier:()=>"hash"});expect(result).toMatchObject({ok:true,status:"created"});});
});

describe("preview and SQL package safety",()=>{
  it("keeps raw CSV out of browser state and hidden fields",()=>{const actions=read("app/admin/users/import/actions.ts");const client=read("app/admin/users/import/import-client.tsx");expect(actions).not.toContain("rawCsv?:");expect(client).not.toContain('name="raw_csv"');expect(actions).toContain("previewIntegrity");});
  it("uses shared encrypted atomic preview RPCs",()=>{const store=read("lib/account-preview-store.ts");expect(store).toContain("aes-256-gcm");expect(store).toContain("vam062_create_account_preview");expect(store).toContain("vam062_consume_account_preview");expect(store).not.toContain("new Map")});
  it("preflight inventories columns, constraints, functions, grants, RLS, policies and relationships",()=>{const sql=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_PREFLIGHT.sql");for(const token of ["information_schema.columns","pg_constraint","pg_extension","pg_get_functiondef","has_function_privilege","has_table_privilege","relforcerowsecurity","pg_policies","relationships","eligible"])expect(sql).toContain(token);});
  it("migration rejects policy and relationship conflicts before material DDL",()=>{const sql=read("supabase_migrations/062_review_only_account_admin_rls_foundation.sql");expect(sql.indexOf("unexpected existing policies")).toBeLessThan(sql.indexOf("create table public.account_rls_package_state"));expect(sql).toContain("season-program relationship mismatch");expect(sql).toContain("batch-season relationship mismatch");expect(sql).toContain("s.season_id is not null");expect(sql).not.toContain("s.season_id is null or")});
  it("rollback removes only package objects and restores enabled/forced RLS flags",()=>{const sql=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_ROLLBACK.sql");expect(sql).toContain("rollback state incomplete");expect(sql).toContain("rls_was_enabled");expect(sql).toContain("rls_was_forced");expect(sql).not.toMatch(/drop function (?!public\.vam062_)/);expect(sql).not.toMatch(/drop table public\.(admin_users|people|person_season_memberships)/);});
  it("protects rollback state and includes exact verification contracts",()=>{const forward=read("supabase_migrations/062_review_only_account_admin_rls_foundation.sql"),rollback=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_ROLLBACK.sql"),post=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_POST_APPLY_VERIFY.sql"),pre=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_PREFLIGHT.sql");expect(forward).toContain("revoke all on public.account_rls_package_state from service_role");expect(rollback).toContain("state_checksum<>");expect(post).toContain("package_functions_service_only");expect(pre).toContain("section_status")});
  it("proves exact compatible conflict targets before material DDL",()=>{const sql=read("supabase_migrations/062_review_only_account_admin_rls_foundation.sql");const ddl=sql.indexOf("create table public.account_rls_package_state");for(const target of ["UNIQUE (email)","UNIQUE (user_id, program_id, season_id)","UNIQUE (person_id, season_id, role)"]){expect(sql.indexOf(target)).toBeGreaterThan(-1);expect(sql.indexOf(target)).toBeLessThan(ddl)}expect(sql).toContain("i.indpred is null");expect(sql).toContain("i.indexprs is null");expect(sql).toContain("indisnullsnotdistinct")});
  it("preserves policy grouping through exact expression comparison",()=>{for(const path of ["supabase_migrations/062_review_only_account_admin_rls_foundation.sql","docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_PREFLIGHT.sql","docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_POST_APPLY_VERIFY.sql"]){const sql=read(path);expect(sql).not.toContain("[[:space:]()]");expect(sql).not.toContain("punctuation");expect(sql).toContain("qual=")}});
  it("authenticates the rollback table manifest before drops",()=>{const sql=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_ROLLBACK.sql");expect(sql.indexOf("authenticated table manifest mismatch")).toBeLessThan(sql.indexOf("drop table public.account_import_previews"));for(const token of ["information_schema.columns","relrowsecurity","package table grants mismatch","package table policy mismatch"])expect(sql).toContain(token)});
  it("uses independent exact post-apply policy specifications",()=>{const sql=read("docs/audits/sql/design_only/VAM_OS_ACCOUNT_ADMIN_RLS_POST_APPLY_VERIFY.sql");expect(sql).toContain("a.qual<>e.q");expect(sql).toContain("s.season_id IS NOT NULL");expect(sql).toContain("unexpected_policies");expect(sql).toContain("ordinary_dml_denied")});
  it("harness proves identity roles and cross-season topology before authorization",()=>{const source=read("scripts/account-rls-isolation-harness.mjs");for(const token of ["jwtOk","database_role","ueh_seasons_distinct","membership_topology","same_program_cross_season_denied","privilege_denial","rls_filter"])expect(source).toContain(token)});  it("API harness fails closed without inputs and emits sanitized JSON",()=>{const run=spawnSync(process.execPath,["scripts/account-rls-isolation-harness.mjs"],{encoding:"utf8"});expect(run.status).toBe(1);expect(JSON.parse(run.stdout)).toEqual({pass:false,reason:"missing_config",results:[]});expect(run.stdout).not.toMatch(/jwt|https?:|apikey/i);});
});
