import { describe,expect,it,vi } from "vitest";
import { resolveAuthOwnership } from "@/lib/account-auth-ownership";
const client=(pages:any[][],invite:any)=>{let n=0;return{auth:{admin:{listUsers:vi.fn(async()=>({data:{users:pages[Math.min(n++,pages.length-1)]??[]},error:null})),inviteUserByEmail:vi.fn(async()=>invite)}}}};
describe("shared Auth ownership adapter",()=>{
 it("classifies preexisting without invitation",async()=>{const c=client([[{id:"old",email:"A@X.test"}]],{});expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"preexisting",deleteAllowed:false});expect(c.auth.admin.inviteUserByEmail).not.toHaveBeenCalled()});
 it("grants deletion authority only for explicit provider id",async()=>{const c=client([[],[{id:"new",email:"a@x.test"}]],{data:{user:{id:"new"}},error:null});expect(await resolveAuthOwnership(c,"a@x.test")).toEqual({state:"proven_created",id:"new",deleteAllowed:true,evidence:"provider_id"})});
 it.each([["one",[[ ],[{id:"race",email:"a@x.test"}]],"ambiguous"],["none",[[],[]],"not_found"],["multiple",[[],[{id:"a",email:"a@x.test"},{id:"b",email:"A@X.TEST"}]],"ambiguous"]])("omitted id %s never grants deletion",async(_n,pages,state)=>{const result=await resolveAuthOwnership(client(pages as any[][],{data:{user:{}},error:null}),"a@x.test");expect(result).toMatchObject({state,deleteAllowed:false})});
 it("detects duplicate pre-operation matches",async()=>{const result=await resolveAuthOwnership(client([[{id:"a",email:"a@x.test"},{id:"b",email:"a@x.test"}]],{}),"a@x.test");expect(result).toMatchObject({state:"ambiguous",deleteAllowed:false})});
 it("does not upgrade an inconsistent provider id",async()=>{const c=client([[],[{id:"other",email:"a@x.test"}]],{data:{user:{id:"provider"}},error:null});expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"ambiguous",deleteAllowed:false})});
 it("treats provider error plus a concurrent match as ambiguous",async()=>{const c=client([[],[{id:"race",email:"a@x.test"}]],{data:null,error:{message:"conflict"}});expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"ambiguous",deleteAllowed:false})});
 it("retry after omitted-id ambiguity becomes preexisting without delete authority",async()=>{const c=client([[],[{id:"race",email:"a@x.test"}],[{id:"race",email:"a@x.test"}]],{data:{user:{}},error:null});expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"ambiguous",deleteAllowed:false});expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"preexisting",deleteAllowed:false})});
 it("lookup failure never permits provider mutation or deletion",async()=>{const c:any=client([[]],{});c.auth.admin.listUsers=vi.fn(async()=>({data:null,error:{message:"offline"}}));expect(await resolveAuthOwnership(c,"a@x.test")).toMatchObject({state:"failed",deleteAllowed:false});expect(c.auth.admin.inviteUserByEmail).not.toHaveBeenCalled()});
 it("manual, sync and CSV paths all import the shared adapter",()=>{for(const path of ["lib/admin-users.ts","lib/account-import-server.ts"]){const source=require("node:fs").readFileSync(path,"utf8");expect(source).toContain("resolveAuthOwnership")}expect(require("node:fs").readFileSync("lib/account-mutation-orchestrator.ts","utf8")).toContain("deleteAllowed")});
});
