import { describe,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));vi.mock("@/lib/supabase-server",()=>({getSupabaseServiceRoleClient:()=>null}));
import {createAccountPreview,consumeAccountPreview,type AccountPreviewPersistence}from "@/lib/account-preview-store";
function memory():AccountPreviewPersistence&{rows:Map<string,any>}{const rows=new Map<string,any>();return{rows,async create(i){rows.set(i.id,i)},async consume(i){const r=rows.get(i.id);if(!r||r.actorId!==i.actorId||r.secretHash!==i.secretHash||Date.parse(r.expiresAt)<=Date.now())return null;rows.delete(i.id);return r}}}
describe("shared encrypted preview contract",()=>{
 it("atomically consumes once without storing raw CSV",async()=>{const p=memory(),v=await createAccountPreview("actor","private,csv",p);expect(JSON.stringify(Array.from(p.rows.values()))).not.toContain("private,csv");expect((await consumeAccountPreview("actor",v.id,v.integrity,p)).ok).toBe(true);expect((await consumeAccountPreview("actor",v.id,v.integrity,p)).ok).toBe(false)});
 it("rejects actor mismatch, tampering and expiry",async()=>{const p=memory(),v=await createAccountPreview("actor","csv",p);expect((await consumeAccountPreview("other",v.id,v.integrity,p)).ok).toBe(false);expect((await consumeAccountPreview("actor",v.id,"tampered",p)).ok).toBe(false);const expired=memory();expired.consume=async()=>null;expect((await consumeAccountPreview("actor",v.id,v.integrity,expired)).ok).toBe(false)});
 it("fails closed on shared-store outage",async()=>{const p:AccountPreviewPersistence={create:async()=>{throw Error()},consume:async()=>{throw Error()}};await expect(createAccountPreview("actor","csv",p)).rejects.toThrow();await expect(consumeAccountPreview("actor","00000000-0000-0000-0000-000000000000","A".repeat(43),p)).rejects.toThrow()});
});
